### ISSUE TITLE
ImportError: No module named singledispatch

### ISSUE THREAD

**Issue by shaunwh** [PPMESSAGE/ppmessage-lite-server#2]
我第一步是直接
bash set-up-ppmessage-on-debian-or-ubuntu.sh
出现了这个问题
Traceback (most recent call last):
  File "/usr/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 70, in <module>
    import packaging.version
ImportError: No module named packaging.version
Finish install the requirements of PPMessage Lite Server.
请问如何解决呢

**Comment by shaunwh** [comment]
root@ecs-mall-dev:/home/ppmessage-lite-server/ppmessage/scripts# bash set-up-ppmessage-on-debian-or-ubuntu.sh
Ign http://cn.archive.ubuntu.com trusty InRelease
Hit http://cn.archive.ubuntu.com trusty-updates InRelease
Hit http://cn.archive.ubuntu.com trusty-backports InRelease
Hit http://cn.archive.ubuntu.com trusty Release.gpg
Hit http://cn.archive.ubuntu.com trusty-updates/main Sources
Hit http://cn.archive.ubuntu.com trusty-updates/restricted Sources
Hit http://cn.archive.ubuntu.com trusty-updates/universe Sources
Hit http://cn.archive.ubuntu.com trusty-updates/multiverse Sources
Hit http://cn.archive.ubuntu.com trusty-updates/main amd64 Packages
Hit http://cn.archive.ubuntu.com trusty-updates/restricted amd64 Packages
Hit http://cn.archive.ubuntu.com trusty-updates/universe amd64 Packages
Hit http://cn.archive.ubuntu.com trusty-updates/multiverse amd64 Packages
Hit http://cn.archive.ubuntu.com trusty-updates/main i386 Packages
Hit http://cn.archive.ubuntu.com trusty-updates/restricted i386 Packages
Hit http://cn.archive.ubuntu.com trusty-updates/universe i386 Packages
Hit http://cn.archive.ubuntu.com trusty-updates/multiverse i386 Packages
Hit http://cn.archive.ubuntu.com trusty-updates/main Translation-en
Hit http://cn.archive.ubuntu.com trusty-updates/multiverse Translation-en
Hit http://cn.archive.ubuntu.com trusty-updates/restricted Translation-en
Hit http://cn.archive.ubuntu.com trusty-updates/universe Translation-en
Hit http://cn.archive.ubuntu.com trusty Release
Hit http://cn.archive.ubuntu.com trusty-backports/main Sources
Hit http://cn.archive.ubuntu.com trusty-backports/restricted Sources
Hit http://cn.archive.ubuntu.com trusty-backports/universe Sources
Hit http://cn.archive.ubuntu.com trusty-backports/multiverse Sources
Hit http://cn.archive.ubuntu.com trusty-backports/main amd64 Packages
Hit http://cn.archive.ubuntu.com trusty-backports/restricted amd64 Packages
Hit http://cn.archive.ubuntu.com trusty-backports/universe amd64 Packages
Hit http://cn.archive.ubuntu.com trusty-backports/multiverse amd64 Packages
Hit http://cn.archive.ubuntu.com trusty-backports/main i386 Packages
Hit http://cn.archive.ubuntu.com trusty-backports/restricted i386 Packages
Hit http://cn.archive.ubuntu.com trusty-backports/universe i386 Packages
Get:1 http://security.ubuntu.com trusty-security InRelease [65.9 kB]
Hit http://cn.archive.ubuntu.com trusty-backports/multiverse i386 Packages
Hit http://cn.archive.ubuntu.com trusty-backports/main Translation-en
Hit http://cn.archive.ubuntu.com trusty-backports/multiverse Translation-en
Hit http://cn.archive.ubuntu.com trusty-backports/restricted Translation-en
Hit http://cn.archive.ubuntu.com trusty-backports/universe Translation-en
Hit http://cn.archive.ubuntu.com trusty/main Sources
Hit http://cn.archive.ubuntu.com trusty/restricted Sources
Hit http://cn.archive.ubuntu.com trusty/universe Sources
Hit http://cn.archive.ubuntu.com trusty/multiverse Sources
Hit http://cn.archive.ubuntu.com trusty/main amd64 Packages
Hit http://cn.archive.ubuntu.com trusty/restricted amd64 Packages
Hit http://cn.archive.ubuntu.com trusty/universe amd64 Packages
Hit http://cn.archive.ubuntu.com trusty/multiverse amd64 Packages
Hit http://cn.archive.ubuntu.com trusty/main i386 Packages
Hit http://cn.archive.ubuntu.com trusty/restricted i386 Packages
Hit http://cn.archive.ubuntu.com trusty/universe i386 Packages
Hit http://cn.archive.ubuntu.com trusty/multiverse i386 Packages
Hit http://cn.archive.ubuntu.com trusty/main Translation-en
Hit http://cn.archive.ubuntu.com trusty/multiverse Translation-en
Hit http://cn.archive.ubuntu.com trusty/restricted Translation-en
Hit http://cn.archive.ubuntu.com trusty/universe Translation-en
Ign http://cn.archive.ubuntu.com trusty/main Translation-en_US
Ign http://cn.archive.ubuntu.com trusty/multiverse Translation-en_US
Ign http://cn.archive.ubuntu.com trusty/restricted Translation-en_US
Ign http://cn.archive.ubuntu.com trusty/universe Translation-en_US
Get:2 http://security.ubuntu.com trusty-security/main Sources [127 kB]
Get:3 http://security.ubuntu.com trusty-security/restricted Sources [4,637 B]
Get:4 http://security.ubuntu.com trusty-security/universe Sources [49.9 kB]
Get:5 http://security.ubuntu.com trusty-security/multiverse Sources [3,194 B]
Get:6 http://security.ubuntu.com trusty-security/main amd64 Packages [593 kB]
Get:7 http://security.ubuntu.com trusty-security/restricted amd64 Packages [13.4 kB]
Get:8 http://security.ubuntu.com trusty-security/universe amd64 Packages [154 kB]
Get:9 http://security.ubuntu.com trusty-security/multiverse amd64 Packages [4,139 B]
Get:10 http://security.ubuntu.com trusty-security/main i386 Packages [553 kB]
Get:11 http://security.ubuntu.com trusty-security/restricted i386 Packages [13.1 kB]
Get:12 http://security.ubuntu.com trusty-security/universe i386 Packages [154 kB]
Get:13 http://security.ubuntu.com trusty-security/multiverse i386 Packages [4,278 B]
Hit http://security.ubuntu.com trusty-security/main Translation-en
Hit http://security.ubuntu.com trusty-security/multiverse Translation-en
Hit http://security.ubuntu.com trusty-security/restricted Translation-en
Hit http://security.ubuntu.com trusty-security/universe Translation-en
Fetched 1,738 kB in 11s (147 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libjpeg62-turbo-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libjpeg8-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 252 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
autoconf is already the newest version.
automake is already the newest version.
g++ is already the newest version.
gcc is already the newest version.
gfortran is already the newest version.
libblas-dev is already the newest version.
liblapack-dev is already the newest version.
libncurses5-dev is already the newest version.
libopus-dev is already the newest version.
libtool is already the newest version.
pkg-config is already the newest version.
python is already the newest version.
python-dev is already the newest version.
apt-file is already the newest version.
libatlas-base-dev is already the newest version.
libmp3lame-dev is already the newest version.
libopencore-amrnb-dev is already the newest version.
libopencore-amrwb-dev is already the newest version.
redis-server is already the newest version.
libfdk-aac-dev is already the newest version.
apt-utils is already the newest version.
git is already the newest version.
libffi-dev is already the newest version.
libfreetype6-dev is already the newest version.
libmagic1 is already the newest version.
libpcre3 is already the newest version.
libpcre3-dev is already the newest version.
libpng12-dev is already the newest version.
libssl-dev is already the newest version.
openssl is already the newest version.
sudo is already the newest version.
wget is already the newest version.
python-pip is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 252 not upgraded.
Traceback (most recent call last):
  File "/usr/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 70, in <module>
    import packaging.version
ImportError: No module named packaging.version
Finish install the requirements of PPMessage Lite Server.

**Comment by shaunwh** [comment]
1、root@ecs-mall-dev:/home# git clone https://github.com/PPMESSAGE/ppmessage-lite-server.git
Cloning into 'ppmessage-lite-server'...
remote: Counting objects: 691, done.
remote: Compressing objects: 100% (464/464), done.
remote: Total 691 (delta 241), reused 638 (delta 188), pack-reused 0
Receiving objects: 100% (691/691), 3.44 MiB | 1.03 MiB/s, done.
Resolving deltas: 100% (241/241), done.
Checking connectivity... done.
2、进入到pp的目录
root@ecs-mall-dev:/home# ll
total 12
drwxr-xr-x  3 root root 4096 Mar  9 11:37 ./
drwxr-xr-x 22 root root 4096 Dec  7 10:52 ../
drwxr-xr-x  4 root root 4096 Mar  9 11:37 ppmessage-lite-server/
root@ecs-mall-dev:/home# cd ppmessage-lite-server/
root@ecs-mall-dev:/home/ppmessage-lite-server#
3、到脚本目录去执行set-up
root@ecs-mall-dev:/home/ppmessage-lite-server# bash ppmessage/scripts/
set-up-ppmessage-on-debian-or-ubuntu.sh  set-up-ppmessage-on-mac.sh               windows-requirements.txt
root@ecs-mall-dev:/home/ppmessage-lite-server# bash ppmessage/scripts/set-up-ppmessage-on-debian-or-ubuntu.sh
Ign http://cn.archive.ubuntu.com trusty InRelease
Hit http://cn.archive.ubuntu.com trusty-updates InRelease
Hit http://cn.archive.ubuntu.com trusty-backports InRelease
Hit http://cn.archive.ubuntu.com trusty Release.gpg
Hit http://cn.archive.ubuntu.com trusty-updates/main Sources
Hit http://cn.archive.ubuntu.com trusty-updates/restricted Sources
Hit http://cn.archive.ubuntu.com trusty-updates/universe Sources
Hit http://cn.archive.ubuntu.com trusty-updates/multiverse Sources
Hit http://cn.archive.ubuntu.com trusty-updates/main amd64 Packages
Hit http://cn.archive.ubuntu.com trusty-updates/restricted amd64 Packages
Hit http://cn.archive.ubuntu.com trusty-updates/universe amd64 Packages
Hit http://cn.archive.ubuntu.com trusty-updates/multiverse amd64 Packages
Hit http://cn.archive.ubuntu.com trusty-updates/main i386 Packages
Hit http://cn.archive.ubuntu.com trusty-updates/restricted i386 Packages
Hit http://cn.archive.ubuntu.com trusty-updates/universe i386 Packages
Hit http://cn.archive.ubuntu.com trusty-updates/multiverse i386 Packages
Hit http://cn.archive.ubuntu.com trusty-updates/main Translation-en
Hit http://cn.archive.ubuntu.com trusty-updates/multiverse Translation-en
Hit http://cn.archive.ubuntu.com trusty-updates/restricted Translation-en
Hit http://cn.archive.ubuntu.com trusty-updates/universe Translation-en
Hit http://cn.archive.ubuntu.com trusty Release
Hit http://security.ubuntu.com trusty-security InRelease
Hit http://cn.archive.ubuntu.com trusty-backports/main Sources
Hit http://cn.archive.ubuntu.com trusty-backports/restricted Sources
Hit http://cn.archive.ubuntu.com trusty-backports/universe Sources
Hit http://cn.archive.ubuntu.com trusty-backports/multiverse Sources
Hit http://cn.archive.ubuntu.com trusty-backports/main amd64 Packages
Hit http://cn.archive.ubuntu.com trusty-backports/restricted amd64 Packages
Hit http://cn.archive.ubuntu.com trusty-backports/universe amd64 Packages
Hit http://cn.archive.ubuntu.com trusty-backports/multiverse amd64 Packages
Hit http://cn.archive.ubuntu.com trusty-backports/main i386 Packages
Hit http://cn.archive.ubuntu.com trusty-backports/restricted i386 Packages
Hit http://cn.archive.ubuntu.com trusty-backports/universe i386 Packages
Hit http://cn.archive.ubuntu.com trusty-backports/multiverse i386 Packages
Hit http://cn.archive.ubuntu.com trusty-backports/main Translation-en
Hit http://cn.archive.ubuntu.com trusty-backports/multiverse Translation-en
Hit http://security.ubuntu.com trusty-security/main Sources
Hit http://cn.archive.ubuntu.com trusty-backports/restricted Translation-en
Hit http://cn.archive.ubuntu.com trusty-backports/universe Translation-en
Hit http://cn.archive.ubuntu.com trusty/main Sources
Hit http://cn.archive.ubuntu.com trusty/restricted Sources
Hit http://cn.archive.ubuntu.com trusty/universe Sources
Hit http://cn.archive.ubuntu.com trusty/multiverse Sources
Hit http://cn.archive.ubuntu.com trusty/main amd64 Packages
Hit http://cn.archive.ubuntu.com trusty/restricted amd64 Packages
Hit http://cn.archive.ubuntu.com trusty/universe amd64 Packages
Hit http://cn.archive.ubuntu.com trusty/multiverse amd64 Packages
Hit http://cn.archive.ubuntu.com trusty/main i386 Packages
Hit http://cn.archive.ubuntu.com trusty/restricted i386 Packages
Hit http://security.ubuntu.com trusty-security/restricted Sources
Hit http://cn.archive.ubuntu.com trusty/universe i386 Packages
Hit http://cn.archive.ubuntu.com trusty/multiverse i386 Packages
Hit http://cn.archive.ubuntu.com trusty/main Translation-en
Hit http://cn.archive.ubuntu.com trusty/multiverse Translation-en
Hit http://cn.archive.ubuntu.com trusty/restricted Translation-en
Hit http://security.ubuntu.com trusty-security/universe Sources
Hit http://cn.archive.ubuntu.com trusty/universe Translation-en
Hit http://security.ubuntu.com trusty-security/multiverse Sources
Ign http://cn.archive.ubuntu.com trusty/main Translation-en_US
Ign http://cn.archive.ubuntu.com trusty/multiverse Translation-en_US
Ign http://cn.archive.ubuntu.com trusty/restricted Translation-en_US
Ign http://cn.archive.ubuntu.com trusty/universe Translation-en_US
Hit http://security.ubuntu.com trusty-security/main amd64 Packages
Hit http://security.ubuntu.com trusty-security/restricted amd64 Packages
Hit http://security.ubuntu.com trusty-security/universe amd64 Packages
Hit http://security.ubuntu.com trusty-security/multiverse amd64 Packages
Hit http://security.ubuntu.com trusty-security/main i386 Packages
Hit http://security.ubuntu.com trusty-security/restricted i386 Packages
Hit http://security.ubuntu.com trusty-security/universe i386 Packages
Hit http://security.ubuntu.com trusty-security/multiverse i386 Packages
Hit http://security.ubuntu.com trusty-security/main Translation-en
Hit http://security.ubuntu.com trusty-security/multiverse Translation-en
Hit http://security.ubuntu.com trusty-security/restricted Translation-en
Hit http://security.ubuntu.com trusty-security/universe Translation-en
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libjpeg62-turbo-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libjpeg8-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 252 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
autoconf is already the newest version.
automake is already the newest version.
g++ is already the newest version.
gcc is already the newest version.
gfortran is already the newest version.
libblas-dev is already the newest version.
liblapack-dev is already the newest version.
libncurses5-dev is already the newest version.
libopus-dev is already the newest version.
libtool is already the newest version.
pkg-config is already the newest version.
python is already the newest version.
python-dev is already the newest version.
apt-file is already the newest version.
libatlas-base-dev is already the newest version.
libmp3lame-dev is already the newest version.
libopencore-amrnb-dev is already the newest version.
libopencore-amrwb-dev is already the newest version.
redis-server is already the newest version.
libfdk-aac-dev is already the newest version.
apt-utils is already the newest version.
git is already the newest version.
libffi-dev is already the newest version.
libfreetype6-dev is already the newest version.
libmagic1 is already the newest version.
libpcre3 is already the newest version.
libpcre3-dev is already the newest version.
libpng12-dev is already the newest version.
libssl-dev is already the newest version.
openssl is already the newest version.
sudo is already the newest version.
wget is already the newest version.
python-pip is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 252 not upgraded.
Traceback (most recent call last):
  File "/usr/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 70, in <module>
    import packaging.version
ImportError: No module named packaging.version
Finish install the requirements of PPMessage Lite Server.
root@ecs-mall-dev:/home/ppmessage-lite-server#
4、出现ImportError: No module named packaging.version

**Comment by dingguijin** [comment]
https://github.com/pypa/setuptools/issues/937

**Comment by dingguijin** [comment]
https://odedrabhavesh.blogspot.jp/2017/02/importerror-no-module-named.html

**Comment by dingguijin** [comment]
sudo su root

apt-get purge -y python-pip

wget https://bootstrap.pypa.io/get-pip.py

python ./get-pip.py

apt-get install python-pip

**Comment by shaunwh** [comment]
感谢楼主的耐心指导，原来是pip的问题，升级一下就可以了
sudo su root

apt-get purge -y python-pip

wget https://bootstrap.pypa.io/get-pip.py

python ./get-pip.py

apt-get install python-pip
